### ISSUE TITLE
fingerprinted object path should be normalized

### ISSUE THREAD

**Issue by oupala** [christophercliff/metalsmith-fingerprint#7]
I'm trying to use this plugin and I'm close to succeed.

> create a duplicate of index.css with a fingerprinted filename

This works well.

> create a fingerprint object on the Metalsmith metadata

This works almost well. But it seems that the created object in metalsmith has no normalized path. As a consequence, the way of accessing the object is different depending of if I'm on linux or on windows :
- on linux `<link href="/{{fingerprint.[css/app.css]}}" rel="stylesheet" type="text/css" />`
- on window `<link href="/{{fingerprint.[css\\app.css]}}" rel="stylesheet" type="text/css" />`

This makes impossible to use this plugin when developing on windows and integrating on linux.

Normalizing the path should make the plugin OS agnostic.

**Comment by oupala** [comment]
My pull request is just a try but at least it works on my windows system.

It might be quick and dirty, but feel free to improve it.

And I have absolutely no idea how to test this, I won't be able to add test to this pull request. I'm sorry for this but I've done my best.

**Comment by CumpsD** [comment]
I would very much love to see this PR merged and a new version pushed, I am developing on both Windows and Linux and that's giving a lot of problems.

**Comment by CumpsD** [comment]
In the mean time, you can always do this:

``` js
var fixFingerprint = function () {
    'use strict';

    return function (files, metalsmith, done) {
        var metadata = metalsmith.metadata(),
            fingerprint  = metadata.fingerprint,
            newFingerprint = {};

        for (var key in fingerprint) {
            var newKey = key.replace(/\\/g, '/');
            var newValue = fingerprint[key].replace(/\\/g, '/');

            newFingerprint[newKey] = newValue;
        }

        metadata.fingerprint = newFingerprint;

        done();
    };
};
```

And use it:
``` js
        .use(fingerprint({ pattern: '{styles,scripts}/**/*.{css,js}' }))
        .use(fixFingerprint())
```

That will also give a cross platform working solution while waiting for a PR.

**Comment by oupala** [comment]
@christophercliff I'd be glad if you can merge my pull request.

**Comment by christophercliff** [comment]
Fixed in #8

**Comment by flegris-orange** [comment]
It appears that the issue is not fixed yet as it does not work on my windows machine, please reopen this issue.

I'm willing to test any potential solution on my env.

**Comment by flegris-orange** [comment]
#8 was correctly fixing the problem as in this state: https://github.com/christophercliff/metalsmith-fingerprint/blob/b1f635a5e9d6de37ede1fdd3f450861b76de5768
b1f635a5e9d6de37ede1fdd3f450861b76de5768/lib/index.js

Tested and validated on Windows.

**Comment by oupala** [comment]
Ok, let's recap the commits and the pull requests trying to fix this issue.

There has been 4 commits and 2 pull requests.

1. first pull request #8

- first commit ce89aa916d8459ab97494f5bdf8f7405090d8d36 : was working, but needed some linting
- second commit b1f635a5e9d6de37ede1fdd3f450861b76de5768 : was also working, linted, but @christophercliff wanted a much simpler solution
- third commit e2fba8590a45d2591df6c457ec5148861c15d6d8 : was not working :-( but **was merged**

2. second pull request #9

- first commit 22e56406783dda815c57ecc08f65d40f2c2ba82a : was working, but **not merged**

As you can see the only merged pull request was merged at a state were it was not working.

There is still two commits **that work** and could be merged. The first one is the most *elegant* while the second one seems more *simpler*.

- commit b1f635a5e9d6de37ede1fdd3f450861b76de5768 : was also working, linted, but @christophercliff wanted a much simpler solution
- commit 22e56406783dda815c57ecc08f65d40f2c2ba82a : was working, but **not merged**

**Comment by oupala** [comment]
Hey @christophercliff, you added the **pull request appreciated** label.

There **is** a pull request.

If I could I would add the **merge appreciated** label!

**Comment by flegris-orange** [comment]
I would greatly appreciate to see any pull request merged. Any news about that?

**Comment by oupala** [comment]
I created a new pull request #13 so that you can merge it easily.
